update settings file

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -1,10 +1,13 @@
 #!/bin/bash
 
-# Start containers with compose
 bin/stop
 docker-compose up -d
-bin/migrate || docker-compose down && exit
 
-if [ "$1" != "-d" ]; then
-    bin/logs
+if ! bin/migrate > /dev/null 2>&1 ; then
+    echo -e "\n[*] Stopping all containers due to failed migration attempt\n"
+    docker-compose down
+    exit
 fi
+
+# Print out logs if -d is not provided
+if [ "$1" != "-d" ]; then bin/logs; fi
